FROM docker:dind

# Instalar git y otras herramientas necesarias
RUN apk add --no-cache git bash

# Establecer el directorio de trabajo
WORKDIR /benchmarks

# Clonar el repositorio con los benchmarks
RUN git clone https://github.com/KidmanC/Dockerfile .

# Script de entrada
CMD ["sh", "-c", "dockerd & sleep 5 && cd Dockerfile && chmod +x run-benchmark.sh && ./run-benchmark.sh"]