FROM docker:dind

# Instalar git y otras herramientas necesarias
RUN apk add --no-cache git bash

# Establecer el directorio de trabajo
WORKDIR /benchmarks

# Clonar el repositorio con los benchmarks
RUN git clone https://github.com/KidmanC/Docker .

# Listar contenido para debug
RUN ls -la

# Script de entrada
CMD ["sh", "-c", "dockerd & sleep 5 && cd /benchmarks && ls -la && chmod +x ./run-benchmarks.sh && ./run-benchmarks.sh"]